# Generated by Django 5.2.4 on 2025-07-14 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20250714_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="L'utilisateur doit avoir au moins 15 ans (RGPD)", null=True, validators=[django.core.validators.MinValueValidator(15)]),
        ),
    ]
